from schemas import HeritagePlace

HERITAGE_PLACES = [
    HeritagePlace(
        id="taj-mahal",
        name="Taj Mahal",
        state="Uttar Pradesh",
        location="Agra, Uttar Pradesh",
        category="Monument",
        short_description="A white marble mausoleum built by Shah Jahan in memory of Mumtaz Mahal.",
        description="The Taj Mahal is an ivory-white marble mausoleum on the south bank of the river Yamuna.",
        history="Commissioned in 1632 by the Mughal emperor Shah Jahan, it took roughly 20 years and thousands of artisans to complete. It is a UNESCO World Heritage Site and one of the New7Wonders of the World.",
        culture="The Taj Mahal blends Persian, Islamic and Indian architectural styles, and remains a symbol of eternal love across Indian culture.",
        dance="Kathak, the classical dance of North India, historically flourished in the Mughal courts of Agra.",
        art="Intricate pietra dura (stone inlay) work with semi-precious stones decorates the marble surfaces.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj-Mahal.jpg/640px-Taj-Mahal.jpg",
        images=[
            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj-Mahal.jpg/640px-Taj-Mahal.jpg",
        ],
        videos=[
            {"title": "Taj Mahal Documentary", "url": "https://www.youtube.com/results?search_query=taj+mahal+documentary"},
        ],
        latitude=27.1751,
        longitude=78.0421,
        tags=["mughal", "monument", "unesco", "agra", "marble"],
        popularity=100,
    ),
    HeritagePlace(
        id="hawa-mahal",
        name="Hawa Mahal",
        state="Rajasthan",
        location="Jaipur, Rajasthan",
        category="Palace",
        short_description="The 'Palace of Winds', famous for its honeycomb facade of 953 small windows.",
        description="Hawa Mahal is a palace built from red and pink sandstone, part of the City Palace of Jaipur.",
        history="Built in 1799 by Maharaja Sawai Pratap Singh, it allowed royal women to observe street festivities without being seen, following the purdah tradition.",
        culture="Jaipur's culture is rich with Rajasthani folk music, colorful festivals like Teej and Gangaur, and vibrant bazaars.",
        dance="Ghoomar, the traditional Rajasthani folk dance performed by women in flowing skirts, originated in this region.",
        art="Famous for Blue Pottery, miniature paintings and intricate mirror-work (Shisha) embroidery.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Hawa_Mahal_2011.jpg/640px-Hawa_Mahal_2011.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Hawa_Mahal_2011.jpg/640px-Hawa_Mahal_2011.jpg"],
        videos=[{"title": "Hawa Mahal Walkthrough", "url": "https://www.youtube.com/results?search_query=hawa+mahal"}],
        latitude=26.9239,
        longitude=75.8267,
        tags=["palace", "jaipur", "rajasthan", "pink city"],
        popularity=90,
    ),
    HeritagePlace(
        id="khajuraho",
        name="Khajuraho Group of Monuments",
        state="Madhya Pradesh",
        location="Khajuraho, Madhya Pradesh",
        category="Temple",
        short_description="A UNESCO World Heritage temple complex famed for its Nagara-style architecture and sculpture.",
        description="A group of Hindu and Jain temples known for their nagara-style architectural symbolism and intricate carvings.",
        history="Built between 950 and 1050 CE by the Chandela dynasty, only about 20 of the original 85 temples survive today.",
        culture="The annual Khajuraho Dance Festival celebrates classical Indian dance forms against the backdrop of the illuminated temples.",
        dance="Kathak and Odissi performances are showcased every year during the Khajuraho Dance Festival.",
        art="Renowned for elaborate stone carvings depicting deities, everyday life and intricate ornamentation.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Kandariya_Mahadeva_Temple.jpg/640px-Kandariya_Mahadeva_Temple.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Kandariya_Mahadeva_Temple.jpg/640px-Kandariya_Mahadeva_Temple.jpg"],
        videos=[{"title": "Khajuraho Temples", "url": "https://www.youtube.com/results?search_query=khajuraho+temples"}],
        latitude=24.8318,
        longitude=79.9199,
        tags=["temple", "unesco", "chandela", "sculpture"],
        popularity=80,
    ),
    HeritagePlace(
        id="hampi",
        name="Hampi",
        state="Karnataka",
        location="Hampi, Karnataka",
        category="Ruins",
        short_description="The ruined capital of the Vijayanagara Empire, set among giant boulders on the Tungabhadra river.",
        description="Hampi was the capital of the Vijayanagara Empire and today is a UNESCO World Heritage Site scattered with ancient temples and ruins.",
        history="Founded in the 14th century, Hampi flourished as one of the richest cities in the world before being sacked in 1565.",
        culture="Hampi hosts the annual Hampi Utsav, celebrating Karnataka's music, dance and heritage.",
        dance="Yakshagana, a traditional dance-drama form of coastal Karnataka, draws from the region's epics and folklore.",
        art="Stone chariot carvings at the Vittala Temple and intricate temple gopurams (towers) are architectural highlights.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Stone_Chariot%2C_Hampi.jpg/640px-Stone_Chariot%2C_Hampi.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Stone_Chariot%2C_Hampi.jpg/640px-Stone_Chariot%2C_Hampi.jpg"],
        videos=[{"title": "Hampi Ruins", "url": "https://www.youtube.com/results?search_query=hampi+ruins"}],
        latitude=15.3350,
        longitude=76.4600,
        tags=["ruins", "unesco", "vijayanagara", "karnataka"],
        popularity=75,
    ),
    HeritagePlace(
        id="konark-sun-temple",
        name="Konark Sun Temple",
        state="Odisha",
        location="Konark, Odisha",
        category="Temple",
        short_description="A 13th-century temple shaped like a colossal chariot dedicated to the Sun God.",
        description="The Konark Sun Temple is designed as a giant stone chariot with 24 wheels, drawn by seven horses.",
        history="Built around 1250 CE by King Narasimhadeva I of the Eastern Ganga dynasty, it is a UNESCO World Heritage Site.",
        culture="The Konark Dance Festival brings classical Indian dance forms to life every year at the temple grounds.",
        dance="Odissi, one of India's oldest classical dance forms, originated in the temples of Odisha, including Konark.",
        art="The temple walls are covered with detailed stone carvings of wheels, horses and celestial figures.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Konark_Temple.jpg/640px-Konark_Temple.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Konark_Temple.jpg/640px-Konark_Temple.jpg"],
        videos=[{"title": "Konark Sun Temple", "url": "https://www.youtube.com/results?search_query=konark+sun+temple"}],
        latitude=19.8876,
        longitude=86.0945,
        tags=["temple", "unesco", "odisha", "sun temple"],
        popularity=70,
    ),
    HeritagePlace(
        id="ajanta-caves",
        name="Ajanta Caves",
        state="Maharashtra",
        location="Aurangabad, Maharashtra",
        category="Caves",
        short_description="Rock-cut Buddhist cave monuments dating from the 2nd century BCE, famed for their paintings.",
        description="The Ajanta Caves comprise 30 rock-cut Buddhist cave monuments featuring paintings and sculptures.",
        history="Constructed in two phases, the 2nd century BCE and the 5th century CE, the caves were rediscovered in 1819.",
        culture="The caves reflect Buddhist religious art and the patronage of trade guilds and royalty of ancient India.",
        dance="Classical Indian dance poses are depicted in several fresco panels within the caves, hinting at ancient performance traditions.",
        art="World-famous for fresco-style paintings depicting the Jataka tales and the life of the Buddha.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Ajanta_Caves_Cave_1.jpg/640px-Ajanta_Caves_Cave_1.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Ajanta_Caves_Cave_1.jpg/640px-Ajanta_Caves_Cave_1.jpg"],
        videos=[{"title": "Ajanta Caves Paintings", "url": "https://www.youtube.com/results?search_query=ajanta+caves"}],
        latitude=20.5519,
        longitude=75.7033,
        tags=["caves", "buddhist", "unesco", "paintings"],
        popularity=72,
    ),
    HeritagePlace(
        id="meenakshi-temple",
        name="Meenakshi Amman Temple",
        state="Tamil Nadu",
        location="Madurai, Tamil Nadu",
        category="Temple",
        short_description="A historic Hindu temple dedicated to Meenakshi, known for its towering gopurams.",
        description="A vast temple complex with 14 gopurams (gateway towers) covered in thousands of colourful sculptures.",
        history="The current structure was largely rebuilt during the 16th-17th centuries under the Nayak rulers of Madurai.",
        culture="The annual Meenakshi Thirukalyanam festival re-enacts the divine marriage of Meenakshi and Sundareswarar.",
        dance="Bharatanatyam, one of India's oldest classical dance forms, has deep roots in Tamil Nadu's temple traditions.",
        art="The temple's 'Hall of a Thousand Pillars' showcases exceptional Dravidian stone sculpture.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Meenakshi_Amman_Temple.jpg/640px-Meenakshi_Amman_Temple.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Meenakshi_Amman_Temple.jpg/640px-Meenakshi_Amman_Temple.jpg"],
        videos=[{"title": "Meenakshi Temple Madurai", "url": "https://www.youtube.com/results?search_query=meenakshi+temple+madurai"}],
        latitude=9.9195,
        longitude=78.1193,
        tags=["temple", "dravidian", "tamil nadu", "gopuram"],
        popularity=78,
    ),
    HeritagePlace(
        id="qutub-minar",
        name="Qutub Minar",
        state="Delhi",
        location="New Delhi, Delhi",
        category="Monument",
        short_description="A 73-metre tall minaret of red sandstone and marble, the tallest brick minaret in the world.",
        description="Qutub Minar is a UNESCO World Heritage Site built to mark the beginning of Muslim rule in India.",
        history="Construction was started in 1192 by Qutb-ud-din Aibak and completed by his successors over the following decades.",
        culture="Delhi's layered history brings together Mughal, Sultanate and colonial influences visible across the city.",
        dance="Delhi's cultural calendar features Kathak performances, historically patronised by the Delhi Sultanate and Mughal courts.",
        art="Verses from the Quran and intricate geometric patterns are carved into the minaret's sandstone surface.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Qutb_Minar_Complex.jpg/640px-Qutb_Minar_Complex.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Qutb_Minar_Complex.jpg/640px-Qutb_Minar_Complex.jpg"],
        videos=[{"title": "Qutub Minar Delhi", "url": "https://www.youtube.com/results?search_query=qutub+minar"}],
        latitude=28.5245,
        longitude=77.1855,
        tags=["monument", "delhi", "unesco", "minaret"],
        popularity=85,
    ),
    HeritagePlace(
        id="mysore-palace",
        name="Mysore Palace",
        state="Karnataka",
        location="Mysuru, Karnataka",
        category="Palace",
        short_description="A historical palace and the official residence of the Wadiyar dynasty of Mysore.",
        description="One of the most visited monuments in India, illuminated with nearly 100,000 lights during Dasara.",
        history="The current palace was built between 1897 and 1912 after the old wooden palace was destroyed by fire.",
        culture="The Mysuru Dasara festival, celebrated with grand processions, is centred around this palace.",
        dance="Traditional folk dances such as Dollu Kunitha are performed during the Dasara festivities.",
        art="Indo-Saracenic architecture blending Hindu, Muslim, Rajput and Gothic styles decorates the palace interiors.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Mysore_Palace.jpg/640px-Mysore_Palace.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Mysore_Palace.jpg/640px-Mysore_Palace.jpg"],
        videos=[{"title": "Mysore Palace Dasara", "url": "https://www.youtube.com/results?search_query=mysore+palace"}],
        latitude=12.3052,
        longitude=76.6552,
        tags=["palace", "karnataka", "dasara", "wadiyar"],
        popularity=82,
    ),
    HeritagePlace(
        id="red-fort",
        name="Red Fort",
        state="Delhi",
        location="New Delhi, Delhi",
        category="Fort",
        short_description="A historic Mughal fort of red sandstone that served as the main residence of Mughal emperors.",
        description="The Red Fort was the principal residence of the emperors of the Mughal dynasty for nearly 200 years.",
        history="Built in 1639 by Emperor Shah Jahan, it is a UNESCO World Heritage Site and the site of the annual Independence Day flag hoisting.",
        culture="Every year on 15 August, the Prime Minister of India hoists the national flag at the Red Fort.",
        dance="Sound and light shows at the fort narrate Mughal-era stories through music and dramatised dance sequences.",
        art="Ornate marble inlay work and Mughal-era gardens (Hayat Bakhsh Bagh) reflect the era's craftsmanship.",
        image_url="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Red_Fort_in_Delhi_03.jpg/640px-Red_Fort_in_Delhi_03.jpg",
        images=["https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Red_Fort_in_Delhi_03.jpg/640px-Red_Fort_in_Delhi_03.jpg"],
        videos=[{"title": "Red Fort Delhi", "url": "https://www.youtube.com/results?search_query=red+fort+delhi"}],
        latitude=28.6562,
        longitude=77.2410,
        tags=["fort", "mughal", "delhi", "unesco"],
        popularity=88,
    ),
]

# quick lookup helpers -----------------------------------------------------

def all_places():
    return HERITAGE_PLACES


def get_by_id(place_id: str):
    for p in HERITAGE_PLACES:
        if p.id == place_id:
            return p
    return None


def get_states():
    return sorted({p.state for p in HERITAGE_PLACES})
